version: "3"
services:
  notes:
    build:
      context: . # 当前目录
      dockerfile: Dockerfile # 基于 Dockerfile 构建
    image: notes # 依赖于当前 Dockerfile 创建镜像
    container_name: notes-service
    ports:
      - 3100:3100
