# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: set ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.TENG_XUN_YUN_ID_RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "122.51.127.235" >> ~/.ssh/known_hosts

      - name: deploy # 部署 # git clone git@github.com:fantienan/notes.git
        run: |
          ssh root@122.51.127.235 "
            cd /home/study;
            rm -rf notes;
            git clone https://${{secrets.USERNAMR_FOR_GITHUB}}:${{secrets.PASSWORD_FOR_GITHUB}}@github.com/fantienan/notes.git;
            git checkout main;
            git pull origin main;
            git remote remove origin;
            cp -rf /home/study/notes/notes/* /home/study/notes/
            docker-compose build notes-service; 
            docker-compose up -d;
          "
      - name: delete ssh key
        run: rm -rf ~/.ssh/id_rsa
